### ISSUE TITLE
[Error] Initial Skills / Knwoledge Skills / Trade Skills / Languages Allowance

### ISSUE THREAD

**Issue by eaganlai** [pazindorb/dc20rpg#2]
**Submitted below to google form instead.**

It seems that the initial allowance of the them is 3/0/0/0.

But they should be as below instead:
Skills: 5+INT
Knowledge: 0
Trades: 3
Languages: 2

Screencap for reference:
![image](https://github.com/pazindorb/dc20rpg/assets/74284983/45f01f2c-3a70-4589-b9c3-dee7884854a4)

**Comment by pazindorb** [comment]
Hi, thank you for your Report. It works as intended because background should provide 5 skill points, 3 trade points, 2 lang points. Backgrounds don't exist in DC20 yet but I did preparation in order to deal with that. 

There was Alpha background inside compendiums but I accidentally removed it in 0.7 update. Please create your own for now (as you would with any other item).

Once again thank you!

![image](https://github.com/pazindorb/dc20rpg/assets/56399197/40b9758c-bc79-48a9-9128-0e71abb5daa9)
